use POST body, encode keys in script, use /etc/default for old settings

diff --git a/mf910-info/usr/bin/mf910-password b/mf910-info/usr/bin/mf910-password
--- a/mf910-info/usr/bin/mf910-password
+++ b/mf910-info/usr/bin/mf910-password
@@ -1,23 +1,50 @@
 #!/bin/bash
 # $1 = target interface
-# $2 = management key (encoded)
-# $3 = new wifi password
+# $2 = new wifi password
+# $3 = new admin password
 
 INTERFACE=$1
-KEY=$2
-NEWPASS=$3
+NEWWIFI=$2
+NEWADMIN=$3
 
 echo -n "Identifying $INTERFACE... "
 ADDRESS=$(ip -f inet -o addr show $1 2>/dev/null | sed -e 's|.*inet \(.*\)/.*|\1|g')
 MODEM=$(echo $ADDRESS| sed -e 's/\.[0-9]*$/.1/g')
 echo "$MODEM."
 
-echo -n "Login... "
-curl -sL --interface $INTERFACE 'http://'$MODEM'/goform/goform_set_cmd_process?isTest=false&goformId=LOGIN&password='$KEY -H 'Referer: http://'$MODEM'/index.html'
-
 echo -n "Fetching IMEI... "
-IMEI=$(curl -s -X GET --interface $INTERFACE 'http://'$MODEM'/goform/goform_get_cmd_process?'$MULTI'isTest=false&cmd=imei&page=0&data_per_page=500&mem_store=1&tags=10&order_by=order+by+id+desc' -H 'Referer: http://'$MODEM'/index.html')
+IMEI=$(curl -s -X GET --interface $INTERFACE 'http://'$MODEM'/goform/goform_get_cmd_process?'$MULTI'isTest=false&cmd=imei&page=0&data_per_page=500&mem_store=1&tags=10&order_by=order+by+id+desc' -H 'Referer: http://'$MODEM'/index.html' | jq -r .imei)
 echo $IMEI
 
-echo -n "Updating wifi password... "
-#curl -sL --interface $INTERFACE 'http://'$MODEM'/goform/goform_set_cmd_process?isTest=false&goformId=SET_WIFI_MULTI_BAND_SETTINGS&isTest=false&m_ssid_enable=0&m_band_enable=0&wifi_multi_band_set=1&security_mode=WPAPSKWPA2PSK&ssid='$SSID'&wifi_band=b&cipher=1&security_shared_mode=1&passphrase='$NEWPASS -H 'Referer: http://'$MODEM'/index.html'
+. /etc/default/mifi.$IMEI
+
+if [ -z "$ADMINKEY" ]; then
+  echo "Missing keys in mifi.$IMEI."
+  exit 1
+fi
+if [ -z "$WIFIKEY" ]; then
+  echo "Missing keys in mifi.$IMEI."
+  exit 1
+fi
+
+function encode {
+  B64=$( echo -n $1 | base64 )
+  HTTP=$( echo -n $B64 | jq -s -R -r @uri )
+  echo -n $HTTP
+}
+
+echo -n "Login... "
+curl -sL --interface $INTERFACE 'http://'$MODEM'/goform/goform_set_cmd_process' -H 'Referer: http://'$MODEM'/index.html' --data 'isTest=false&goformId=LOGIN&password='$(encode $ADMINKEY)
+
+if [ "$WIFIKEY" != "$NEWWIFI" ]; then
+  echo -n "Updating wifi password... "
+  curl -sL --interface $INTERFACE 'http://'$MODEM'/goform/goform_set_cmd_process' -H 'Referer: http://'$MODEM'/index.html' --data 'isTest=false&goformId=SET_WIFI_MULTI_BAND_SETT0INGS&isTest=false&m_ssid_enable=0&m_band_enable=0&wifi_multi_band_set=1&security_mode=WPAPSKWPA2PSK&ssid='$IMEI'&wifi_band=b&cipher=1&security_shared_mode=1&passphrase='$( encode $NEWWIFI) -H 'Referer: http://'$MODEM'/index.html'
+fi
+
+if [ "$ADMINKEY" != "$NEWADMIN" ]; then
+  echo -n "Updating management password... "
+  curl -sL --interface $INTERFACE 'http://'$MODEM'/goform/goform_set_cmd_process' -H 'Referer: http://'$MODEM'/index.html' --data 'newPassword='$(encode $NEWADMIN)'&oldPassword=$(encode $ADMINKEY)&goformId=CHANGE_PASSWORD&isTest=false'
+fi
+
+echo "WIFIKEY=$NEWWIFI" > /etc/default/mifi.$IMEI
+echo "ADMINKEY=$NEWADMIN" >> /etc/default/mifi.$IMEI
