continue on acceptable errors, test: trap to release lock on exit

diff --git a/monroe-experiments/usr/bin/monroe-experiments b/monroe-experiments/usr/bin/monroe-experiments
--- a/monroe-experiments/usr/bin/monroe-experiments
+++ b/monroe-experiments/usr/bin/monroe-experiments
@@ -51,6 +51,7 @@ flock -n 42 || {
   logger -t monroe-experiments "lock file present";
   exit 1;
 }
+trap "flock -u 42" EXIT
 
 mk_disk "ping";
 mk_disk "metadata";
@@ -59,13 +60,19 @@ mk_disk "mplane";
 docker rm $(docker ps -aq) 2>/dev/null || true;
 MNS="ip netns exec monroe";
 
-if [ -z "$(docker ps --no-trunc|grep $URL_NOOP)" ]; then
-  #docker pull $URL_NOOP 2> /dev/null;
+if [ ! -e /var/run/netns/monroe ]; then
+  # stop any running containers
+  CID=$(docker ps --no-trunc | grep $URL_NOOP | awk '{print $1}' | head -n 1)
+  if [ ! -z "$CID" ]; then
+    docker stop -t 0 $CID;
+  fi
+
+  docker pull $URL_NOOP 2> /dev/null;
   docker run -d --net=bridge $URL_NOOP;
-  CID=$(docker ps --no-trunc | grep $URL_NOOP | awk '{print $1}' | head -n 1);
-  PID=$(docker inspect -f '{{.State.Pid}}' $CID);
+  CID=$(docker ps --no-trunc | grep $URL_NOOP | awk '{print $1}' | head -n 1)
+  PID=$(docker inspect -f '{{.State.Pid}}' $CID)
   mkdir -p /var/run/netns;
-  rm /var/run/netns/monroe 2>/dev/null;
+  rm /var/run/netns/monroe 2>/dev/null || true;
   ln -s /proc/$PID/ns/net /var/run/netns/monroe;
 
   # rename the docker bridge interface 'eth0' to 'metadata'
@@ -74,17 +81,21 @@ if [ -z "$(docker ps --no-trunc|grep $URL_NOOP)" ]; then
   $MNS ip link set eth0 name metadata;
   $MNS ifconfig metadata $IP up;
 
-  $MNS multi_client -c /etc/multi-netns-monroe.yaml& 
+  $MNS multi_client -d -c /etc/multi-netns-monroe.yaml&
+fi
+
+if [ ! -e /var/run/netns/monroe ]; then
+  echo "network namespace is missing";
+  exit 1;
 fi
 
 CID=$(docker ps --no-trunc | grep $URL_NOOP | awk '{print $1}' | head -n 1)
 
-INTERFACES="usb0 usb1 usb2 wlan0 eth0 wwan2";
+INTERFACES="usb0" "usb1" "usb2" "wlan0" "eth0" "wwan2";
 for IF in $INTERFACES; do
   if [ ! -z "$($MNS ip link|grep $IF)" ]; then continue; fi
   if [ -z "$(ip link|grep $IF)" ]; then continue; fi
 
-  ip link del montmp || true;
   ip link add link $IF montmp type macvlan;
   ip link set montmp netns monroe;
   $MNS ip link set montmp name $IF;
@@ -93,7 +104,7 @@ for IF in $INTERFACES; do
   $MNS ifconfig $IF up;
 done
 
-for IF in "usb0" "usb1" "usb2" "wwan0" "eth0" "wwan2"; do
+for IF in $INTERFACES; do
   if [ ! -z "$($MNS ip link|grep $IF)" ]; then
     if [ -z "$(docker ps --no-trunc|grep $URL_PING|grep $IF)" ]; then
       docker pull $URL_PING 2> /dev/null;
