update monroe-maintenance window to remove more stale docker images

diff --git a/monroe-experiments/usr/bin/monroe-maintenance b/monroe-experiments/usr/bin/monroe-maintenance
--- a/monroe-experiments/usr/bin/monroe-maintenance
+++ b/monroe-experiments/usr/bin/monroe-maintenance
@@ -7,19 +7,36 @@ export PATH=/usr/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/b
 echo 1 > /monroe/maintenance/enabled
 echo "routine maintenance window" > /monroe/maintenance/reason
 
-docker stop -t 0 $(docker ps -q) || true
-systemctl stop docker || true
+systemctl start docker && {
+    docker stop -t 0 $(docker ps -q) || true
 
-# unmount and delete all folders in /experiments
-grep /experiments /proc/mounts | cut -f1 -d' ' | xargs umount || true
-rm -r /experiments/monroe/*
-rm -r /experiments/user/*
+    # unmount and delete all folders in /experiments
+    grep /experiments /proc/mounts | cut -f1 -d' ' | xargs umount || true
+    rm -r /experiments/monroe/*
+    rm -r /experiments/user/*
+
+    # cleanup stale containers
+    # remove monroe- containers other than what is currently scheduled
+    CURRENT_SCHEDULES=$(atq|awk '{print $1}'|xargs -n 1 at -c|grep start|awk '{print $2}')
+    TASK_IMAGES=$(docker images|grep ^monroe-|awk '{print $1}')
+    for s in $CURRENT_SCHEDULES; do
+        TASK_IMAGES=$(echo "$TASK_IMAGES"|grep -v $s);
+    done
+    docker rmi $TASK_IMAGES
+    # remove any non-monroe container
+    docker images | grep -v 'IMAGE ID' | grep -v ^monroe | grep -v $KAU_REPO | awk '{print $3}' | xargs -n 1 docker rmi
+    # remove any untagged container (old versions of base experiments)
+    docker images | grep none | awk '{print $3}' | xargs -n 1 docker rmi
+
+    systemctl stop docker || true
+}
 
 echo 0 > /monroe/maintenance/enabled
 rm /monroe/maintenance/reason
 
 # check for issues and restore maintenance flag
 biteback -f
+
 
 # redeploy and start continuous base experiments
 monroe-experiments
